version: "3.8"

services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: "minioadmin"
      MINIO_ROOT_PASSWORD: "minioadmin"
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "admin"
    command: start-dev
    volumes:
      - keycloak-data:/opt/keycloak/data

  app:
    build:
      context: ./src
    container_name: flask_app
    ports:
      - "5000:5000"
    environment:
      MINIO_ENDPOINT: "http://minio:9000"
      MINIO_ACCESS_KEY: "minioadmin"
      MINIO_SECRET_KEY: "minioadmin"
      BUCKET_NAME: "files"
      KEYCLOAK_URL: "http://keycloak:8080"
    depends_on:
      - minio
      - keycloak

volumes:
  minio-data:
  keycloak-data: